name: zapdart
description: Library for ZAP flutter apps
version: 0.0.1

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # for zapdart (remove when made into proper package)
  shared_preferences: ^2.0.7
  edit_distance: ^0.5.0-nullsafety.0
  pin_code_text_field: ^1.8.0
  qr_flutter: ^4.0.0
  another_flushbar: ^1.10.24
  encrypt: ^5.0.1
  base58check: ^2.0.0
  retry: ^3.1.0
  decimal: ^1.3.0
  google_fonts: ^2.1.0
  universal_platform: ^1.0.0+1
  image_picker: ^0.8.4
  extended_image: ^4.2.1
  image: ^3.0.2
  intl_phone_number_input: ^0.7.0+2
  debounce_throttle: ^2.0.0
  email_validator: ^2.0.1
  uuid: ^3.0.4
  flutter_svg: ^1.1.0
  device_info_plus: ^3.2.1
  zxcvbn: ^1.0.0

flutter:
  assets:
    - assets/
